apiVersion: v2
name: common
description: A Helm chart for Kubernetes
icon: https://i0.wp.com/divistant.com/wp-content/uploads/2020/10/color_favicon.png

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.1"

# Artifact Hub
annotations:
  artifacthub.io/changes: |
    - Added cool feature
    - Fixed minor bug    
  artifacthub.io/changes: |
    - kind: added
      description: Cool feature
      links:
        - name: Github Issue
          url: https://github.com/issue-url
        - name: Github PR
          url: https://github.com/pr-url
    - kind: fixed
      description: Minor bug
      links:
        - name: Github Issue
          url: https://github.com/issue-url    
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/images: |
    - name: img1
      image: nginx:latest
    - name: img2
      image: nginx:latest
      whitelisted: true    
  artifacthub.io/crds: |
    - kind: MyKind
      version: v1
      name: mykind
      displayName: My Kind
      description: Some nice description    
  artifacthub.io/crdsExamples: |
    - apiVersion: v1
      kind: MyKind
      metadata:
        name: mykind
      spec:
        replicas: 1    
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: link1
      url: https://link1.url
    - name: link2
      url: https://link2.url    
  artifacthub.io/maintainers: |
    - name: user1
      email: user1@email.com
    - name: user2
      email: user2@email.com    
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/prerelease: "false"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/artifact-hub/artifact-hub
    - url: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack    
  artifacthub.io/screenshots: |
    - title: Sample screenshot 1
      url: https://example.com/screenshot1.jpg
    - title: Sample screenshot 2
      url: https://example.com/screenshot2.jpg    
  artifacthub.io/signKey: |
    fingerprint: C874011F0AB405110D02105534365D9472D7468F
    url: https://keybase.io/hashicorp/pgp_keys.asc